/*
 * Created on 10 Jan 2017 ( Time 18:00:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.Publisher;

/**
 * Business Service Interface for entity Publisher.
 */
public interface PublisherService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param code
	 * @return entity
	 */
	Publisher findById( Integer code  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Publisher> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Publisher save(Publisher entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Publisher update(Publisher entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Publisher create(Publisher entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param code
	 */
	void delete( Integer code );


}
