/*
 * Created on 10 Jan 2017 ( Time 17:58:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.listitem;

import org.demo.bean.BookOrderItem;
import org.demo.web.common.ListItem;

public class BookOrderItemListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public BookOrderItemListItem(BookOrderItem bookOrderItem) {
		super();

		this.value = ""
			 + bookOrderItem.getBookOrderId()
			 + "|"  + bookOrderItem.getBookId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = bookOrderItem.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
