/*
 * Created on 10 Jan 2017 ( Time 18:00:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.BookOrderItem;
import org.demo.bean.jpa.BookOrderItemEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class BookOrderItemServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public BookOrderItemServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'BookOrderItemEntity' to 'BookOrderItem'
	 * @param bookOrderItemEntity
	 */
	public BookOrderItem mapBookOrderItemEntityToBookOrderItem(BookOrderItemEntity bookOrderItemEntity) {
		if(bookOrderItemEntity == null) {
			return null;
		}

		//--- Generic mapping 
		BookOrderItem bookOrderItem = map(bookOrderItemEntity, BookOrderItem.class);

		return bookOrderItem;
	}
	
	/**
	 * Mapping from 'BookOrderItem' to 'BookOrderItemEntity'
	 * @param bookOrderItem
	 * @param bookOrderItemEntity
	 */
	public void mapBookOrderItemToBookOrderItemEntity(BookOrderItem bookOrderItem, BookOrderItemEntity bookOrderItemEntity) {
		if(bookOrderItem == null) {
			return;
		}

		//--- Generic mapping 
		map(bookOrderItem, bookOrderItemEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}