/*
 * Created on 10 Jan 2017 ( Time 17:58:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.common;

public enum MessageType {
	
	SUCCESS,
	INFO,
	WARNING,
	DANGER;
	
	public String getCss() {
		return name().toLowerCase();
	}
	
}
